services:
  #fintrack:
  #  image: fintrack
  #  build:
  #    context: .
  #    dockerfile: FinTrack/Dockerfile
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "P@ssw0rd"
    ports:
        - 1433:1433

