//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrack.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CountryMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FinTrack.Resources.CountryMessages", typeof(CountryMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DuplicateNameError {
            get {
                return ResourceManager.GetString("DuplicateNameError", resourceCulture);
            }
        }
        
        public static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        public static string Alpha3CodeLengthError {
            get {
                return ResourceManager.GetString("Alpha3CodeLengthError", resourceCulture);
            }
        }
        
        public static string DuplicateAlpha3CodeError {
            get {
                return ResourceManager.GetString("DuplicateAlpha3CodeError", resourceCulture);
            }
        }
        
        public static string Alpha2CodeLengthError {
            get {
                return ResourceManager.GetString("Alpha2CodeLengthError", resourceCulture);
            }
        }
        
        public static string DuplicateAlpha2CodeError {
            get {
                return ResourceManager.GetString("DuplicateAlpha2CodeError", resourceCulture);
            }
        }
    }
}
